In [20]:
import numpy as np

In [21]:
from numeric_ad import Variable

In [22]:

data = np.array(1.0)
x = Variable(data)
print(x.data)

1.0


In [23]:
x.data = np.array(2.0)
print(x.data)

2.0


In [24]:
from numeric_ad import Function, Square

In [25]:
x = Variable(np.array(10))
f = Square()
y = f(x)

print(type(y))
print(y.data)

<class 'numeric_ad.core_simple.Variable'>
100


In [26]:
y.__class__

numeric_ad.core_simple.Variable

In [27]:
print(type(np.array(10)))

<class 'numpy.ndarray'>


In [28]:
import numpy as np

In [130]:
d = 2
p = 4
mat = [np.random.randn(d, d) for i in range(0, p+1)]
autocorrs = [X.T @ X for X in mat]

In [131]:
e = np.eye(d, d)

def Phi(coeffs, k):
    ret = autocorrs[k]
    for l in range(1, p+1):
        ret = ret + coeffs[l-1] @ autocorrs[np.abs(k-l)]
    return ret


def grad_elem(coeffs, l, i, j):
    assert l > 0
    ret = np.zeros_like(autocorrs[0])
    for k in range(1, p+1):
        ret = ret + autocorrs[np.abs(k-l)] @ (Phi(coeffs, k).T)
    return e[j].T @ ret @ e[i]


def gradient(coeffs):
    return [np.array([[grad_elem(coeffs, l, i, j) for j in range(d)] for i in range(d)]) for l in range(1, p+1)]

In [132]:
coeffs = [np.random.randn(d, d) for i in range(1, p+1)]

In [133]:
def loss(coeffs):
    ret = 0.0
    for l in range(1,p+1):
        P = Phi(coeffs, l)
        ret += np.trace(P.T @ P)
    return ret

In [134]:
# expect = -autocorrs[1] / autocorrs[0]
# expect

In [135]:
# Phi([expect], 1)

In [144]:
iters = 5000
lr = 0.005
it_per_epoch = iters / 20

coeffs = [np.random.randn(d, d) for i in range(1, p+1)]
# coeffs = [expect]
print(coeffs)
print(loss(coeffs))

for i in range(iters):
    grads = gradient(coeffs)
    for l in range(1, p+1):
        coeffs[l-1] -= lr * grads[l-1]
        
    if i % it_per_epoch == 0:
        print(loss(coeffs))

coeffs

[array([[-0.51717162, -0.57827594],
       [-0.87466872,  0.33279927]]), array([[ 0.26907431, -0.12513114],
       [-0.57580393, -0.28387675]]), array([[-2.76951235,  1.07364821],
       [ 0.5214606 , -0.14206041]]), array([[ 0.14377408, -0.2031109 ],
       [-1.17681224,  0.76416779]])]
118.55860302082588
95.17073672140204
1.5404560762491382
0.25787638244188205
0.048450244127909416
0.009258762947606103
0.0017745036090437891
0.00034027264521699146
6.525568080406941e-05
1.2514605240974987e-05
2.4000338794005734e-06
4.602754863319795e-07
8.827106489290042e-08
1.6928516257045883e-08
3.2465300390324863e-09
6.226155405602374e-10
1.1940444312102087e-10
2.289923734181064e-11
4.391587597408485e-12
8.422132706132596e-13
1.6151862534619903e-13


[array([[-0.52703012, -0.48385506],
        [-0.98027266, -1.35312352]]),
 array([[-0.81811883,  0.76659693],
        [ 1.31955933,  0.18834048]]),
 array([[ 0.04598175, -0.17626707],
        [ 0.39396047,  1.32588357]]),
 array([[-0.50231195, -0.11876406],
        [-0.81916309, -2.06709342]])]

In [140]:

loss(coeffs)

2.3873492276308332e-14

In [143]:
Phi(coeffs, 4)

array([[1.85144734e-08, 3.45279238e-08],
       [3.95616982e-08, 7.37792094e-08]])